name: ShieldStatusFix
version: '1.0.0'
main: ru.kirushkinx.shieldstatusfix.ShieldStatusFix
api-version: '1.21'
author: kirushkinx
dependencies:
  server:
    packetevents:
      load: BEFORE
      required: true
      join-classpath: true
